println("Hello, world!")
println(5)
println(5+5)
println(5-3.8)
println(5+15-3.2, " ... evaluated!" , "         losts of empty space")
println("Hello!" * " My word!")
println("Hello!" * " My word!"^3)
println("abc!@#%^ .. kyking:;'<,>.?/")
println("\\")
